# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Moterys programuoja
description: > # this means to ignore newlines until "baseurl:"
  Tai mano dienoraštis besimokant programavimo. Tikiuosi, jog įrašai padės ne tik man pačiai geriau suprasti šį amatą, bet ir įkvėpti daugiau moterų rinktis programavimo sritį
baseurl: "" # the subpath of your site, e.g. /blog
logo: "/images/logo.jpg" #figure out the right path
og_image: "/images/logo.jpg"
excerpt_separator: <!--more-->
url: "http://www.girlscode.lt" # the base hostname & protocol for your site
twitter_username: ingavaicia
github_username:  ingava

paginate: 5
paginate_path: "/page:num/"

gems:
  - jekyll-seo-tag
  - jekyll-paginate



# Build settings
markdown: kramdown
theme: minima
